---
- name: Check if NVM is installed
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.nvm"
  register: nvm_install_state

- name: Install NVM
  when: not nvm_install_state.stat.exists | bool
  block:
    - name: Retreive NVM install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
        dest: /tmp/nvm-install.sh
        mode: "0755"

    - name: Execute NVM install script
      ansible.builtin.command: /tmp/nvm-install.sh

    - name: Remove NVM install script
      ansible.builtin.file:
        path: /tmp/nvm-install.sh
        state: absent

- name: Add nvm to path in zshrc
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    marker: "# {mark} NVM ANSIBLE MANAGED"
    block: |
      export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"